### ISSUE TITLE
Add Allure Report generation

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/music-quiz-automation#11]
It will be required for running local tests and tests on Jenkins CI/CD and publishing Allure Reports.

1. Add required dependencies and run Allure report locally.
2. Then add a new feature: Allure Report should attach screenshots if test failed - it will help us to investigate issues.
3. Then add @Step annotation to all PageObject methods so they will appear in Allure report for each tests.

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/music-quiz-automation/pull/13
