### ISSUE TITLE
Generate Allure Report in CI/CD using GitHub pages

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/music-quiz-automation#14]
See:

1. https://dev.to/sadia/host-your-automation-allure-report-on-github-pages-with-github-actions-56a
2. https://learnautomatedtesting.com/blog/how_to_serve_an_allure_report_on_github_pages_a_step_by_step_guide/

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/music-quiz-automation/pull/15
