### ISSUE TITLE
Add job with manual trigger to run all tests at CI/CD

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/music-quiz-automation#16]
Now when we covered our smoke suit it's time to start running full regression and all tests and analyze results - so we need to have Allure Report as well.
Usually full regression not needed per each commit, merge request so let's do triggering it manually.
If your tests need to be updated to work inside CI/Cd - please add such fixes.

Also to run regression maybe you need to pass some data: env, branch. If it's not passed - then use default env and master branch.

Example of manual job with passing data: https://github.com/topsycreed/simplePayTests/blob/SPAY-1272/.github/workflows/test_component.yml

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/music-quiz-automation/pull/17
