### ISSUE TITLE
Add e2e scenario for registration

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/music-quiz-automation#4]
1. You should automate steps for registration
2. Use patterns like PageObjects to store locators and actions
3. Use external data like Excel files to store users
4. Check that test passed until clicking send button (but do not click on it since you're testing a prod env)

!!! Your commit should not contain real user data, only template with columns and examples. Do not put real Name, Surname, login, passwords and other sensitive info !!!

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/music-quiz-automation/pull/6

**Comment by DaryaAndreyuk** [comment]
Done
