### ISSUE TITLE
Add additional checks and negative tests

### ISSUE THREAD

**Issue by topsycreed** [DaryaAndreyuk/music-quiz-automation#7]
For example for positive tests before moving to a next registration tab you can compare values from Excel and real values that inserted to all input fields.

For negative tests try to register without mandatory fields or with invalid phone number, fail the registration process and etc. The goal of the test is to assert that error message appeared on the screen.

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/music-quiz-automation/pull/8

**Comment by DaryaAndreyuk** [comment]
https://github.com/DaryaAndreyuk/music-quiz-automation/pull/9
